version: 0.2

phases:
  #install:
    #runtime-versions:
    #  java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      #- git clone https://github.com/ohbster/GoldWatch_WWW.git . 
      #- mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - target/GoldWatch-$(date +%Y-%m-%d).zip
